name: regcap
channels:
  - conda-forge
dependencies:
  - python=3.8.20
  - pip
  - pip:
      - torch==2.4.1
      - torch-geometric==2.6.1
      - pytorch-lightning==2.4.0
      - torchmetrics==1.5.2
      - numpy==1.24.4
      - gensim==3.8.3
      - nltk==3.9.1
      - tqdm==4.67.1
      - scipy==1.10.1
